{% set name = "onnx" %}
{% set version = "1.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Andrii-Osipov/onnx/archive/refs/tags/1.91.1.main.tar.gz
  sha256: fd23f07e1417d150cc68b5e51066b4c9952f2c6405ebbca65316e88cdeb39010
  patches:
    - patches/0001-dont-hide-all-symbols-and-set-ext-suffix.patch

build:
  number: 0
  entry_points:
    - check-model = onnx.bin.checker:check_model
    - check-node = onnx.bin.checker:check_node
    - backend-test-tools = onnx.backend.test.cmd_tools:main
  skip: True  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - libprotobuf 5.29.3
  host:
    - python
    - pip
    # for py313 numpy 2.1 needs setuptools less than 74
    - setuptools <74
    - wheel
    - pybind11 2.13.6
    - protobuf 5.29.3
    - libprotobuf 5.29.3
    - libabseil 20250127.0
    - numpy 2.0 # [py<313]
    - numpy 2.1 # [py==313]
  run:
    - python
    - protobuf >=4.25.1
    # Drop Python 3.8 support in favor of better NumPy compatibility
    - numpy >=1.19
    - typing-extensions >=4.7.1
    - ml_dtypes >=0.5.0
    # through run_exports
    - libprotobuf
    - libabseil

{% set tests_to_skip = "" %}
# Skip test_regex_full_match and test_regex_invalid_pattern because google-re2 isn't available
{% set tests_to_skip = tests_to_skip + "test_regex_full_match or test_regex_invalid_pattern" %}
# Skip test_image_decoder_decode_jpeg_bgr_cpu, test_image_decoder_decode_jpeg_rgb_cpu, and test_image_decoder_decode_jpeg_grayscale_cpu
# because of "AssertionError: Not equal to tolerance rtol=0.001, atol=1e-07",
# see https://github.com/onnx/onnx/issues/4798
{% set tests_to_skip = tests_to_skip + " or test_image_decoder_decode_jpeg_bgr_cpu or test_image_decoder_decode_jpeg_rgb_cpu or test_image_decoder_decode_jpeg_grayscale_cpu" %}

test:
  imports:
    - onnx
  requires:
    - pip
    # Parameterized tests can raise "TypeError: Parameters must be tuples, but 1 is not (hint: use '(1, )')"
    # if parameterized <0.9.0:
    - parameterized >=0.9.0
    - pillow
    - pytest
  commands:
    - pip check
    - check-model --help
    - check-node --help
    - backend-test-tools --help
    # issue: https://github.com/onnx/onnx/issues/7376
    # tests connected with ShapeInferenceError, TypeInferenceError broken on osx-arm64:
    - pytest --pyargs onnx -k "not ({{ tests_to_skip }})"  # [not (osx and arm64)]

about:
  home: https://onnx.ai
  summary: Open Neural Network Exchange library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Open Neural Network Exchange (ONNX) is the first step toward an open
    ecosystem that empowers AI developers to choose the right tools as their
    project evolves. ONNX provides an open source format for AI models. It
    defines an extensible computation graph model, as well as definitions of
    built-in operators and standard data types. Initially we focus on the
    capabilities needed for inferencing (evaluation).
  doc_url: https://onnx.ai/onnx
  dev_url: https://github.com/onnx/onnx

extra:
  recipe-maintainers:
    - ezyang
    - marcelotrevisani
    - xhochy
