{% set name = "onnx" %}
{% set version = "1.12.0" %}
{% set sha256 = "052ad3d5dad358a33606e0fc89483f8150bb0655c99b12a43aa58b5b7f0cc507" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/onnx/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - check-model = onnx.bin.checker:check_model
    - check-node = onnx.bin.checker:check_node
    - backend-test-tools = onnx.backend.test.cmd_tools:main
  ignore_run_exports:
    - libprotobuf  # [win]

requirements:
  build:
    - {{ compiler('c') }}                     
    - {{ compiler('cxx') }}                   
    - cmake
    - make                                    # [not win]
    - libprotobuf
  host:
    - python
    - pip
    - setuptools
    - wheel
    - protobuf
    - libprotobuf
    - pytest-runner
    - ninja
    - pybind11
    - numpy
  run:
    - python
    - protobuf
    - {{ pin_compatible('libprotobuf') }}
    - {{ pin_compatible('numpy') }}
    - six
    - typing-extensions >=3.6.2.1

test:
  requires:
    - pip
  imports:
    - onnx
  commands:
    - pip check
    - check-model --help
    - check-node --help
    - backend-test-tools --help

about:
  home: https://onnx.ai
  summary: Open Neural Network Exchange library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Open Neural Network Exchange (ONNX) is the first step toward an open
    ecosystem that empowers AI developers to choose the right tools as their
    project evolves. ONNX provides an open source format for AI models. It
    defines an extensible computation graph model, as well as definitions of
    built-in operators and standard data types. Initially we focus on the
    capabilities needed for inferencing (evaluation).
  doc_url: https://github.com/onnx/onnx/blob/main/README.md
  doc_source_url: https://github.com/onnx/onnx/tree/main/docs
  dev_url: https://github.com/onnx/onnx

extra:
  recipe-maintainers:
    - ezyang
    - marcelotrevisani
    - xhochy
