{% set name = "onnx" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d5e983c36037003615e5a02d36b18fc286541bf52de1a78f6cf9f32005a820e

build:
  number: 1
  skip: True  # [py<38]
  entry_points:
    - check-model = onnx.bin.checker:check_model
    - check-node = onnx.bin.checker:check_node
    - backend-test-tools = onnx.backend.test.cmd_tools:main
  missing_dso_whitelist:  # [s390x]
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make          # [not win]
    - libprotobuf {{ libprotobuf }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - pybind11 2.13.6
    # required >=3.20.2 but we have only 3.20.3 with python 3.11 support
    - protobuf {{ libprotobuf }}
    - libprotobuf {{ libprotobuf }}
    - libabseil {{ libabseil }}
    - pytest-runner 6.0.0
    - numpy 2.0 # [py<313]
    - numpy 2.1 # [py==313]
  run:
    - python
    - protobuf >=3.20.2
    - numpy >=1.20
    - typing-extensions >=3.6.2.1
    # through run_exports
    - libprotobuf
    - libabseil

{% set tests_to_skip = "" %}
# Skip test_regex_full_match and test_regex_invalid_pattern because google-re2 isn't available
{% set tests_to_skip = tests_to_skip + "test_regex_full_match or test_regex_invalid_pattern" %}
# Skip test_image_decoder_decode_jpeg_bgr_cpu, test_image_decoder_decode_jpeg_rgb_cpu, and test_image_decoder_decode_jpeg_grayscale_cpu
# because of "AssertionError: Not equal to tolerance rtol=0.001, atol=1e-07",
# see https://github.com/onnx/onnx/issues/4798
{% set tests_to_skip = tests_to_skip + " or test_image_decoder_decode_jpeg_bgr_cpu or test_image_decoder_decode_jpeg_rgb_cpu or test_image_decoder_decode_jpeg_grayscale_cpu" %}

# helper tests (test_to_array_with_external_data, test_make_tensor_raw) fail on big endian,
# see https://github.com/onnx/onnx/issues/2992
{% set tests_to_skip = tests_to_skip + " or test_make_tensor_raw" %}         # [linux and s390x]
{% set tests_to_skip = tests_to_skip + " or test_save_model_with_external_data_multiple_times or test_to_array_with_external_data" %}  # [linux and s390x]

test:
  imports:
    - onnx
  requires:
    - pip
    # Parameterized tests can raise "TypeError: Parameters must be tuples, but 1 is not (hint: use '(1, )')"
    # if parameterized <0.9.0:
    - parameterized >=0.9.0
    - pillow
    - pytest
    # google-re2 is RE2 Python bindings but it's not available on defaults.
    #- google-re2
  commands:
    - pip check
    - check-model --help
    - check-node --help
    - backend-test-tools --help
    - pytest --pyargs onnx -k "not ({{ tests_to_skip }})"

about:
  home: https://onnx.ai
  summary: Open Neural Network Exchange library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Open Neural Network Exchange (ONNX) is the first step toward an open
    ecosystem that empowers AI developers to choose the right tools as their
    project evolves. ONNX provides an open source format for AI models. It
    defines an extensible computation graph model, as well as definitions of
    built-in operators and standard data types. Initially we focus on the
    capabilities needed for inferencing (evaluation).
  doc_url: https://onnx.ai/onnx/
  dev_url: https://github.com/onnx/onnx

extra:
  recipe-maintainers:
    - ezyang
    - marcelotrevisani
    - xhochy
