{% set name = "onnx" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d5e983c36037003615e5a02d36b18fc286541bf52de1a78f6cf9f32005a820e

build:
  number: 0
  skip: True  # [py<38]
  entry_points:
    - check-model = onnx.bin.checker:check_model
    - check-node = onnx.bin.checker:check_node
    - backend-test-tools = onnx.backend.test.cmd_tools:main
  missing_dso_whitelist:  # [s390x]
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make          # [not win]
    - libprotobuf {{ libprotobuf }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - pybind11 2.12.0
    # required >=3.20.2 but we have only 3.20.3 with python 3.11 support
    - protobuf {{ libprotobuf }}
    - libprotobuf {{ libprotobuf }}
    - libabseil {{ libabseil }}
    - pytest-runner 6.0.0
    - numpy 2.0 # [py<313]
    - numpy 2.1 # [py==313]
  run:
    - python
    - protobuf >=3.20.2
    - numpy >=1.20,<2.3
    - typing-extensions >=3.6.2.1
    # through run_exports
    - libprotobuf
    - libabseil

test:
  imports:
    - onnx
  source_files:
    - onnx/test
  requires:
    - pip
    - parameterized
    - pillow
    - pytest
  commands:
    - pip check
    - check-model --help
    - check-node --help
    - backend-test-tools --help
    # Parameterized tests can raise "TypeError: Parameters must be tuples, but 1 is not (hint: use '(1, )')"
    - pytest -vv onnx/test --ignore="onnx/test/data_propagation_test.py" --ignore="onnx/test/function_inference_test.py" --ignore="onnx/test/shape_inference_test.py"

about:
  home: https://onnx.ai
  summary: Open Neural Network Exchange library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Open Neural Network Exchange (ONNX) is the first step toward an open
    ecosystem that empowers AI developers to choose the right tools as their
    project evolves. ONNX provides an open source format for AI models. It
    defines an extensible computation graph model, as well as definitions of
    built-in operators and standard data types. Initially we focus on the
    capabilities needed for inferencing (evaluation).
  doc_url: https://onnx.ai/onnx/
  dev_url: https://github.com/onnx/onnx

extra:
  recipe-maintainers:
    - ezyang
    - marcelotrevisani
    - xhochy
