travis:
  secure:
    BINSTAR_TOKEN: jQRip0EsWlFYcibRV9k8U/JoGXVwTFeU0D3JJdQymH5jsL8vkuAeo2LvETcHvC6JlvZ5r1mJ0ktFHIzB5w+PuchJ2rLmNNRsy6m3xztW3K49es9Ldoe7zXnujaixqkTQg4Q2szfWHRGNqIQrVgz/+I459gpeP0epex5H0M5WQIYIA2QpSzKKPo+JOymHk4hUYVDcoFGcfIzyH3igRfPDtCW5bXExnUcw8uiA826FvXzU2PgVldF3K9OU4jOWA7rZETy+bTe+TC6eJDGQQ8sthImRwtrqrPY3GyMml1NVotX1SabFXmQB2XyWjxxZXg/2u7XayZrqKPIsdNwibX0lyxWVJ59kH9ACwQiL277sVHWKpH+kqqQZnPo69fEm2Flu2YXeo3DrFvpQb/4VNyfyjpadDw9lkoFbE3s7/Nr0yA/Nr8dX+ilbU2jH4KItnHZarfEhe4QJQ/QoT99cVIJQ4K+pAf+Jw5S1t4QrxGjbpNIiUnpl+v9zyN1oqtCYN9EKCIb6XouvxEILFIen7O/hidVMDLLNIOSZs046tzfGWNSPwHVXuP3Vu4IJdaK7VRev/wudYj1UMqCv1cI/2gDUVkyA3IScVEdX+T1zZwDujKHeC3HlrZx9CFRBWWApQrloRDBps56Am31uC9dBYVVbn5DziuARrju/1is115RGTNs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
